// Combat Resources Manager - Defines all combat resource drops
// Organized by combat skill category

class CombatResourcesManager {
    constructor() {
        this.resourceCategories = {
            melee: this.getMeleeResources(),
            ranged: this.getRangedResources(),
            defense: this.getDefenseResources()
        };
    }

    /**
     * Get display name for a combat resource
     * @param {string} resourceKey - Resource identifier
     * @returns {string} - Formatted display name
     */
    getDisplayName(resourceKey) {
        const allResources = {
            ...this.resourceCategories.melee,
            ...this.resourceCategories.ranged,
            ...this.resourceCategories.defense
        };
        
        return allResources[resourceKey] || this.formatResourceName(resourceKey);
    }

    /**
     * Format resource key to display name
     * @param {string} key - Resource key (e.g., 'dragon_scale')
     * @returns {string} - Formatted name (e.g., 'Dragon Scale')
     */
    formatResourceName(key) {
        return key.split('_').map(word => 
            word.charAt(0).toUpperCase() + word.slice(1)
        ).join(' ');
    }

    /**
     * Get all resource keys for a category
     * @param {string} category - 'melee', 'ranged', or 'defense'
     * @returns {Array} - Array of resource keys
     */
    getResourceKeys(category) {
        return Object.keys(this.resourceCategories[category] || {});
    }

    /**
     * Check if a resource belongs to combat category
     * @param {string} resourceKey - Resource identifier
     * @returns {boolean}
     */
    isCombatResource(resourceKey) {
        return this.getResourceKeys('melee').includes(resourceKey) ||
               this.getResourceKeys('ranged').includes(resourceKey) ||
               this.getResourceKeys('defense').includes(resourceKey);
    }

    // ==================== MELEE RESOURCES ====================
    getMeleeResources() {
        return {
            // Low tier drops (1-20)
            'rat_tail': 'Rat Tail',
            'rat_fur': 'Rat Fur',
            'goblin_tooth': 'Goblin Tooth',
            'leather_scraps': 'Leather Scraps',
            'imp_ash': 'Imp Ash',
            'lesser_rune': 'Lesser Rune',
            'beetle_shell': 'Beetle Shell',
            'chitin_fragment': 'Chitin Fragment',
            'dog_fang': 'Dog Fang',
            'torn_hide': 'Torn Hide',
            'rotting_flesh': 'Rotting Flesh',
            'bone_fragment': 'Bone Fragment',
            'bone_shard': 'Bone Shard',
            'skull_piece': 'Skull Piece',
            'goblin_blade': 'Goblin Blade',
            'iron_scraps': 'Iron Scraps',
            'boar_tusk': 'Boar Tusk',
            'tough_hide': 'Tough Hide',
            'broken_sword': 'Broken Sword',
            'copper_coin': 'Copper Coin',

            // Mid-low tier drops (21-40)
            'orc_tooth': 'Orc Tooth',
            'crude_axe': 'Crude Axe',
            'spider_silk': 'Spider Silk',
            'venom_sac': 'Venom Sac',
            'ghoul_claw': 'Ghoul Claw',
            'cursed_bone': 'Cursed Bone',
            'hobgoblin_armor': 'Hobgoblin Armor',
            'iron_blade': 'Iron Blade',
            'werewolf_fang': 'Werewolf Fang',
            'silver_fur': 'Silver Fur',
            'troll_hide': 'Troll Hide',
            'regeneration_gland': 'Regeneration Gland',
            'orc_axe': 'Orc Axe',
            'iron_plate': 'Iron Plate',
            'minotaur_horn': 'Minotaur Horn',
            'battle_axe_head': 'Battle Axe Head',
            'dark_steel': 'Dark Steel',
            'shadow_essence': 'Shadow Essence',
            'ogre_club': 'Ogre Club',
            'thick_bone': 'Thick Bone',

            // Mid tier drops (41-60)
            'scorpion_tail': 'Scorpion Tail',
            'poison_gland': 'Poison Gland',
            'battle_axe': 'Battle Axe',
            'rage_crystal': 'Rage Crystal',
            'spectral_essence': 'Spectral Essence',
            'soul_fragment': 'Soul Fragment',
            'giant_eye': 'Giant Eye',
            'massive_club': 'Massive Club',
            'ancient_blade': 'Ancient Blade',
            'cursed_armor': 'Cursed Armor',
            'hellfire_fang': 'Hellfire Fang',
            'infernal_ash': 'Infernal Ash',
            'chieftain_axe': 'Chieftain Axe',
            'steel_plate': 'Steel Plate',
            'ancient_wrappings': 'Ancient Wrappings',
            'preserved_organs': 'Preserved Organs',
            'stone_wing': 'Stone Wing',
            'granite_claw': 'Granite Claw',
            'wail_essence': 'Wail Essence',
            'spirit_cloth': 'Spirit Cloth',

            // Mid-high tier drops (61-80)
            'giant_bone': 'Giant Bone',
            'boulder_fragment': 'Boulder Fragment',
            'cursed_blade': 'Cursed Blade',
            'dark_plate': 'Dark Plate',
            'harpy_feather': 'Harpy Feather',
            'talon_claw': 'Talon Claw',
            'manticore_tail': 'Manticore Tail',
            'poison_spine': 'Poison Spine',
            'ancient_weapon': 'Ancient Weapon',
            'spectral_armor': 'Spectral Armor',
            'berserker_hide': 'Berserker Hide',
            'rage_gland': 'Rage Gland',
            'chimera_scale': 'Chimera Scale',
            'tri_elemental_core': 'Tri-Elemental Core',
            'vampire_fang': 'Vampire Fang',
            'blood_vial': 'Blood Vial',
            'demon_claw': 'Demon Claw',
            'sulfur_crystal': 'Sulfur Crystal',
            'two_headed_skull': 'Two-Headed Skull',
            'giant_club': 'Giant Club',

            // High tier drops (81-99)
            'vampire_blood': 'Vampire Blood',
            'crimson_cape': 'Crimson Cape',
            'cursed_staff': 'Cursed Staff',
            'dark_orb': 'Dark Orb',
            'golem_core': 'Golem Core',
            'enchanted_stone': 'Enchanted Stone',
            'war_axe': 'War Axe',
            'chief_helmet': 'Chief Helmet',
            'troll_regeneration': 'Troll Regeneration',
            'cave_crystal': 'Cave Crystal',
            'demon_blade': 'Demon Blade',
            'infernal_armor': 'Infernal Armor',
            'frozen_heart': 'Frozen Heart',
            'ice_club': 'Ice Club',
            'dragon_bone': 'Dragon Bone',
            'necrotic_essence': 'Necrotic Essence',
            'black_blade': 'Black Blade',
            'cursed_plate': 'Cursed Plate',
            'abyssal_whip': 'Abyssal Whip',
            'demon_heart': 'Demon Heart',

            // Legendary tier drops (90-99)
            'golem_heart': 'Golem Heart',
            'steel_core': 'Steel Core',
            'wyvern_scale': 'Wyvern Scale',
            'dragon_tooth': 'Dragon Tooth',
            'phylactery_shard': 'Phylactery Shard',
            'death_essence': 'Death Essence',
            'hydra_scale': 'Hydra Scale',
            'regenerating_head': 'Regenerating Head',
            'fire_core': 'Fire Core',
            'molten_essence': 'Molten Essence',
            'greater_demon_horn': 'Greater Demon Horn',
            'hellfire_shard': 'Hellfire Shard',
            'war_core': 'War Core',
            'mithril_plating': 'Mithril Plating',
            'lord_fang': 'Lord Fang',
            'ancient_blood': 'Ancient Blood',
            'shadow_claw': 'Shadow Claw',
            'void_essence': 'Void Essence',
            'behemoth_horn': 'Behemoth Horn',
            'titan_bone': 'Titan Bone',

            // Dragon tier drops (70-99)
            'dragon_scale': 'Dragon Scale',
            'flame_gland': 'Flame Gland',
            'demon_crown': 'Demon Crown',
            'hellfire_core': 'Hellfire Core',
            'adamant_core': 'Adamant Core',
            'living_metal': 'Living Metal',
            'ancient_blade': 'Ancient Blade',
            'hero_armor': 'Hero Armor',
            'ice_core': 'Ice Core',
            'frozen_essence': 'Frozen Essence',
            'pure_blood': 'Pure Blood',
            'vampire_lord_fang': 'Vampire Lord Fang',
            'arch_demon_horn': 'Arch Demon Horn',
            'infernal_heart': 'Infernal Heart',
            'crystal_heart': 'Crystal Heart',
            'prismatic_shard': 'Prismatic Shard',
            'void_shard': 'Void Shard',
            'dimensional_essence': 'Dimensional Essence',
            'dragon_heart': 'Dragon Heart',
            'dragonfire_gland': 'Dragonfire Gland',

            // God tier drops (85-99)
            'balrog_horn': 'Balrog Horn',
            'flame_whip': 'Flame Whip',
            'titan_heart': 'Titan Heart',
            'primordial_stone': 'Primordial Stone',
            'elder_blood': 'Elder Blood',
            'immortal_essence': 'Immortal Essence',
            'death_scythe': 'Death Scythe',
            'soul_reaper': 'Soul Reaper',
            'hydra_heart': 'Hydra Heart',
            'eternal_regeneration': 'Eternal Regeneration',
            'titan_blade': 'Titan Blade',
            'war_essence': 'War Essence',
            'infernal_scale': 'Infernal Scale',
            'hellfire_breath': 'Hellfire Breath',
            'prince_crown': 'Prince Crown',
            'demon_throne_shard': 'Demon Throne Shard',
            'runite_core': 'Runite Core',
            'ancient_mechanism': 'Ancient Mechanism',
            'shadow_scale': 'Shadow Scale',
            'void_breath': 'Void Breath',
            'ancient_scale': 'Ancient Scale',
            'dragon_soul': 'Dragon Soul',
            'demonic_essence': 'Demonic Essence',
            'hell_crown': 'Hell Crown',
            'lich_phylactery': 'Lich Phylactery',
            'undeath_essence': 'Undeath Essence',
            'titan_armor': 'Titan Armor',
            'primordial_weapon': 'Primordial Weapon',
            'commander_blade': 'Commander Blade',
            'death_plate': 'Death Plate',
            'balrog_heart': 'Balrog Heart',
            'eternal_flame': 'Eternal Flame',
            'void_scale': 'Void Scale',
            'dimensional_breath': 'Dimensional Breath',
            'master_phylactery': 'Master Phylactery',
            'necromancy_tome': 'Necromancy Tome',
            'divine_weapon': 'Divine Weapon',
            'war_incarnation': 'War Incarnation',
            'elder_scale': 'Elder Scale',
            'primordial_flame': 'Primordial Flame',
            'king_scale': 'King Scale',
            'dragon_throne_shard': 'Dragon Throne Shard',
            'emperor_crown': 'Emperor Crown',
            'hell_scepter': 'Hell Scepter',
            'primordial_core': 'Primordial Core',
            'creation_essence': 'Creation Essence',
            'death_incarnation': 'Death Incarnation',
            'soul_harvester': 'Soul Harvester',
            'celestial_blade': 'Celestial Blade',
            'heaven_armor': 'Heaven Armor',
            'eternal_phylactery': 'Eternal Phylactery',
            'undeath_crown': 'Undeath Crown',
            'infernal_core': 'Infernal Core',
            'hellfire_heart': 'Hellfire Heart',
            'void_crown': 'Void Crown',
            'dimensional_scepter': 'Dimensional Scepter',
            'divine_essence': 'Divine Essence',
            'godslayer_blade': 'Godslayer Blade'
        };
    }

    // ==================== RANGED RESOURCES ====================
    getRangedResources() {
        return {
            // Low tier drops (1-20)
            'bat_wing': 'Bat Wing',
            'echo_membrane': 'Echo Membrane',
            'wooden_arrow': 'Wooden Arrow',
            'rope': 'Rope',
            'hawk_feather': 'Hawk Feather',
            'sharp_talon': 'Sharp Talon',
            'goblin_bow': 'Goblin Bow',
            'crude_arrow': 'Crude Arrow',
            'scouting_bow': 'Scouting Bow',
            'iron_arrow': 'Iron Arrow',
            'pixie_dust': 'Pixie Dust',
            'tiny_bow': 'Tiny Bow',
            'raven_feather': 'Raven Feather',
            'black_plume': 'Black Plume',
            'bandit_bow': 'Bandit Bow',
            'steel_arrow': 'Steel Arrow',
            'wasp_stinger': 'Wasp Stinger',
            'chitin_wing': 'Chitin Wing',
            'eagle_feather': 'Eagle Feather',
            'predator_talon': 'Predator Talon',

            // Mid-low tier drops (21-40)
            'orc_bow': 'Orc Bow',
            'bone_arrow': 'Bone Arrow',
            'fairy_wing': 'Fairy Wing',
            'enchanted_arrow': 'Enchanted Arrow',
            'vulture_feather': 'Vulture Feather',
            'scavenger_beak': 'Scavenger Beak',
            'shadow_bow': 'Shadow Bow',
            'dark_arrow': 'Dark Arrow',
            'harpy_bow': 'Harpy Bow',
            'wind_feather': 'Wind Feather',
            'iron_crossbow': 'Iron Crossbow',
            'bolt_bundle': 'Bolt Bundle',
            'falcon_feather': 'Falcon Feather',
            'hunter_talon': 'Hunter Talon',
            'imp_bow': 'Imp Bow',
            'flame_arrow': 'Flame Arrow',
            'moth_wing': 'Moth Wing',
            'dust_powder': 'Dust Powder',
            'elven_bow': 'Elven Bow',
            'mithril_arrow': 'Mithril Arrow',

            // Mid tier drops (41-60)
            'throwing_knife': 'Throwing Knife',
            'poison_dart': 'Poison Dart',
            'wyvern_talon': 'Wyvern Talon',
            'scale_arrow': 'Scale Arrow',
            'dark_bow': 'Dark Bow',
            'shadow_bolt': 'Shadow Bolt',
            'dragonfly_wing': 'Dragonfly Wing',
            'compound_eye': 'Compound Eye',
            'sniper_rifle': 'Sniper Rifle',
            'piercing_bolt': 'Piercing Bolt',
            'stone_bow': 'Stone Bow',
            'granite_arrow': 'Granite Arrow',
            'air_essence': 'Air Essence',
            'gust_arrow': 'Gust Arrow',
            'griffin_feather': 'Griffin Feather',
            'razor_talon': 'Razor Talon',
            'spectral_bow': 'Spectral Bow',
            'ghost_arrow': 'Ghost Arrow',
            'tail_spike': 'Tail Spike',
            'venom_barb': 'Venom Barb',

            // Mid-high tier drops (61-80)
            'ranger_bow': 'Ranger Bow',
            'cursed_arrow': 'Cursed Arrow',
            'flame_bow': 'Flame Bow',
            'burning_arrow': 'Burning Arrow',
            'frozen_bow': 'Frozen Bow',
            'ice_shard': 'Ice Shard',
            'giant_feather': 'Giant Feather',
            'massive_talon': 'Massive Talon',
            'shadow_blade': 'Shadow Blade',
            'void_dart': 'Void Dart',
            'elven_longbow': 'Elven Longbow',
            'enchanted_bolt': 'Enchanted Bolt',
            'storm_feather': 'Storm Feather',
            'lightning_quill': 'Lightning Quill',
            'basilisk_scale': 'Basilisk Scale',
            'petrifying_gaze': 'Petrifying Gaze',
            'wind_core': 'Wind Core',
            'cyclone_essence': 'Cyclone Essence',
            'dragon_plume': 'Dragon Plume',
            'fire_talon': 'Fire Talon',

            // High tier drops (81-99)
            'griffin_wing': 'Griffin Wing',
            'lion_claw': 'Lion Claw',
            'master_crossbow': 'Master Crossbow',
            'adamant_bolt': 'Adamant Bolt',
            'wyvern_saddle': 'Wyvern Saddle',
            'rider_bow': 'Rider Bow',
            'knight_bow': 'Knight Bow',
            'royal_arrow': 'Royal Arrow',
            'elemental_bow': 'Elemental Bow',
            'tempest_arrow': 'Tempest Arrow',
            'drake_scale': 'Drake Scale',
            'shadow_breath': 'Shadow Breath',
            'legendary_bow': 'Legendary Bow',
            'runite_arrow': 'Runite Arrow',
            'thunder_feather': 'Thunder Feather',
            'shock_talon': 'Shock Talon',
            'dark_plume': 'Dark Plume',
            'cursed_flame': 'Cursed Flame',
            'demon_bow': 'Demon Bow',
            'hellfire_arrow': 'Hellfire Arrow',

            // Legendary tier drops (90-99)
            'crystal_bow': 'Crystal Bow',
            'prismatic_arrow': 'Prismatic Arrow',
            'storm_wing': 'Storm Wing',
            'lightning_talon': 'Lightning Talon',
            'void_blade': 'Void Blade',
            'dimensional_dart': 'Dimensional Dart',
            'ancient_feather': 'Ancient Feather',
            'primordial_talon': 'Primordial Talon',
            'fire_scale': 'Fire Scale',
            'flame_breath': 'Flame Breath',
            'champion_bow': 'Champion Bow',
            'enchanted_quiver': 'Enchanted Quiver',
            'ice_plume': 'Ice Plume',
            'frozen_flame': 'Frozen Flame',
            'shadow_wing': 'Shadow Wing',
            'storm_core': 'Storm Core',
            'thunder_essence': 'Thunder Essence',
            'dragon_saddle': 'Dragon Saddle',
            'rider_lance': 'Rider Lance',

            // Phoenix tier drops (70-99)
            'phoenix_feather': 'Phoenix Feather',
            'rebirth_ash': 'Rebirth Ash',
            'void_bow': 'Void Bow',
            'dimensional_arrow': 'Dimensional Arrow',
            'ancient_wing': 'Ancient Wing',
            'elder_talon': 'Elder Talon',
            'celestial_bow': 'Celestial Bow',
            'holy_arrow': 'Holy Arrow',
            'storm_scale': 'Storm Scale',
            'lightning_breath': 'Lightning Breath',
            'shadow_plume': 'Shadow Plume',
            'void_flame': 'Void Flame',
            'assassin_bow': 'Assassin Bow',
            'death_dart': 'Death Dart',
            'wind_scale': 'Wind Scale',
            'cyclone_breath': 'Cyclone Breath',
            'lord_bow': 'Lord Bow',
            'divine_arrow': 'Divine Arrow',
            'greater_plume': 'Greater Plume',
            'eternal_flame': 'Eternal Flame',

            // God tier drops (85-99)
            'celestial_wing': 'Celestial Wing',
            'divine_talon': 'Divine Talon',
            'void_scale': 'Void Scale',
            'dimension_breath': 'Dimension Breath',
            'ancient_plume': 'Ancient Plume',
            'primordial_flame': 'Primordial Flame',
            'titan_bow': 'Titan Bow',
            'thunder_titan_arrow': 'Thunder Titan Arrow',
            'shadow_saddle': 'Shadow Saddle',
            'void_lance': 'Void Lance',
            'arch_plume': 'Arch Plume',
            'rebirth_core': 'Rebirth Core',
            'divine_crossbow': 'Divine Crossbow',
            'heaven_bolt': 'Heaven Bolt',
            'storm_heart': 'Storm Heart',
            'tempest_scale': 'Tempest Scale',
            'void_plume': 'Void Plume',
            'dimensional_flame': 'Dimensional Flame',
            'lord_saddle': 'Lord Saddle',
            'dragon_lance': 'Dragon Lance',
            'guardian_plume': 'Guardian Plume',
            'eternal_rebirth': 'Eternal Rebirth',
            'commander_saddle': 'Commander Saddle',
            'war_lance': 'War Lance',
            'elemental_heart': 'Elemental Heart',
            'thunder_core': 'Thunder Core',
            'sky_essence': 'Sky Essence',
            'cloud_bow': 'Cloud Bow',
            'celestial_scale': 'Celestial Scale',
            'divine_breath': 'Divine Breath',
            'arch_void_bow': 'Arch Void Bow',
            'dimension_quiver': 'Dimension Quiver',
            'ancient_storm_scale': 'Ancient Storm Scale',
            'primordial_thunder': 'Primordial Thunder',
            'celestial_flame': 'Celestial Flame',
            'heaven_plume': 'Heaven Plume',
            'void_titan_bow': 'Void Titan Bow',
            'dimension_arrow': 'Dimension Arrow',
            'elder_plume': 'Elder Plume',
            'immortal_flame': 'Immortal Flame',
            'king_plume': 'King Plume',
            'throne_flame': 'Throne Flame',
            'emperor_saddle': 'Emperor Saddle',
            'imperial_lance': 'Imperial Lance',
            'divine_storm': 'Divine Storm',
            'god_thunder': 'God Thunder',
            'titan_wing': 'Titan Wing',
            'heaven_essence': 'Heaven Essence',
            'emperor_bow': 'Emperor Bow',
            'dimension_scepter': 'Dimension Scepter',
            'ancient_divine_scale': 'Ancient Divine Scale',
            'primordial_holy_breath': 'Primordial Holy Breath',
            'primordial_plume': 'Primordial Plume',
            'creation_flame': 'Creation Flame',
            'divine_wing': 'Divine Wing',
            'heaven_bow': 'Heaven Bow',
            'eternal_essence': 'Eternal Essence',
            'immortal_rebirth': 'Immortal Rebirth'
        };
    }

    // ==================== DEFENSE RESOURCES ====================
    getDefenseResources() {
        return {
            // Low tier drops (1-20)
            'boar_hide': 'Boar Hide',
            'tusk_fragment': 'Tusk Fragment',
            'wolf_pelt': 'Wolf Pelt',
            'sharp_fang': 'Sharp Fang',
            'bull_horn': 'Bull Horn',
            'thick_leather': 'Thick Leather',
            'elk_antler': 'Elk Antler',
            'sturdy_hide': 'Sturdy Hide',
            'guard_collar': 'Guard Collar',
            'loyal_fang': 'Loyal Fang',
            'ram_horn': 'Ram Horn',
            'wool_padding': 'Wool Padding',
            'bison_hide': 'Bison Hide',
            'massive_horn': 'Massive Horn',
            'wooden_shield': 'Wooden Shield',
            'goblin_buckler': 'Goblin Buckler',
            'bear_pelt': 'Bear Pelt',
            'claw_guard': 'Claw Guard',
            'iron_shield': 'Iron Shield',
            'captain_helm': 'Captain Helm',

            // Mid-low tier drops (21-40)
            'orc_shield': 'Orc Shield',
            'iron_rim': 'Iron Rim',
            'rhino_horn': 'Rhino Horn',
            'armored_hide': 'Armored Hide',
            'steel_shield': 'Steel Shield',
            'warrior_buckler': 'Warrior Buckler',
            'plated_hide': 'Plated Hide',
            'guard_claw': 'Guard Claw',
            'fortress_shield': 'Fortress Shield',
            'tower_plate': 'Tower Plate',
            'war_collar': 'War Collar',
            'battle_fang': 'Battle Fang',
            'cave_pelt': 'Cave Pelt',
            'stone_claw': 'Stone Claw',
            'troll_shield': 'Troll Shield',
            'regenerating_plate': 'Regenerating Plate',
            'mammoth_tusk': 'Mammoth Tusk',
            'thick_fur': 'Thick Fur',
            'knight_shield': 'Knight Shield',
            'steel_plate': 'Steel Plate',

            // Mid tier drops (41-60)
            'turtle_shell': 'Turtle Shell',
            'fortified_scale': 'Fortified Scale',
            'golem_shield': 'Golem Shield',
            'stone_core': 'Stone Core',
            'elephant_hide': 'Elephant Hide',
            'ivory_guard': 'Ivory Guard',
            'holy_shield': 'Holy Shield',
            'blessed_plate': 'Blessed Plate',
            'plated_troll_hide': 'Plated Troll Hide',
            'iron_guard': 'Iron Guard',
            'juggernaut_plate': 'Juggernaut Plate',
            'massive_shield': 'Massive Shield',
            'guardian_pelt': 'Guardian Pelt',
            'protective_claw': 'Protective Claw',
            'tower_shield': 'Tower Shield',
            'fortress_plate': 'Fortress Plate',
            'charging_horn': 'Charging Horn',
            'plated_hide': 'Plated Hide',
            'iron_bulwark': 'Iron Bulwark',
            'warrior_plate': 'Warrior Plate',

            // Mid-high tier drops (61-80)
            'stone_shield': 'Stone Shield',
            'granite_plate': 'Granite Plate',
            'war_tusk': 'War Tusk',
            'battle_hide': 'Battle Hide',
            'champion_shield': 'Champion Shield',
            'elite_plate': 'Elite Plate',
            'fortress_core': 'Fortress Core',
            'stone_bulwark': 'Stone Bulwark',
            'giant_shield': 'Giant Shield',
            'titan_plate': 'Titan Plate',
            'guardian_bulwark': 'Guardian Bulwark',
            'holy_plate': 'Holy Plate',
            'ancient_shell': 'Ancient Shell',
            'primordial_scale': 'Primordial Scale',
            'beast_armor': 'Beast Armor',
            'battle_hide': 'Battle Hide',
            'battering_horn': 'Battering Horn',
            'siege_plate': 'Siege Plate',
            'colossus_shield': 'Colossus Shield',
            'steel_bulwark': 'Steel Bulwark',

            // High tier drops (81-99)
            'battle_tusk': 'Battle Tusk',
            'war_hide': 'War Hide',
            'berserker_shield': 'Berserker Shield',
            'rage_plate': 'Rage Plate',
            'iron_bulwark': 'Iron Bulwark',
            'guardian_core': 'Guardian Core',
            'war_core': 'War Core',
            'battle_shield': 'Battle Shield',
            'siege_core': 'Siege Core',
            'fortress_bulwark': 'Fortress Bulwark',
            'dragon_shell': 'Dragon Shell',
            'flame_scale': 'Flame Scale',
            'divine_shield': 'Divine Shield',
            'celestial_plate': 'Celestial Plate',
            'mountain_shield': 'Mountain Shield',
            'earth_plate': 'Earth Plate',
            'titan_bulwark': 'Titan Bulwark',
            'primordial_plate': 'Primordial Plate',
            'fortress_heart': 'Fortress Heart',
            'wall_shield': 'Wall Shield',

            // Legendary tier drops (90-99)
            'adamant_shield': 'Adamant Shield',
            'hard_plate': 'Hard Plate',
            'elder_tusk': 'Elder Tusk',
            'ancient_hide': 'Ancient Hide',
            'battle_core': 'Battle Core',
            'war_bulwark': 'War Bulwark',
            'titan_stone': 'Titan Stone',
            'earth_bulwark': 'Earth Bulwark',
            'dragon_guard': 'Dragon Guard',
            'scale_shield': 'Scale Shield',
            'siege_heart': 'Siege Heart',
            'battering_shield': 'Battering Shield',
            'ancient_bulwark': 'Ancient Bulwark',
            'primordial_shield': 'Primordial Shield',
            'war_scale': 'War Scale',
            'battle_shield': 'Battle Shield',
            'fortress_scale': 'Fortress Scale',
            'wall_guard': 'Wall Guard',
            'elder_shell': 'Elder Shell',
            'time_scale': 'Time Scale',

            // God tier drops (85-99)
            'runite_shield': 'Runite Shield',
            'ancient_plate': 'Ancient Plate',
            'primordial_tusk': 'Primordial Tusk',
            'creation_hide': 'Creation Hide',
            'divine_bulwark': 'Divine Bulwark',
            'holy_core': 'Holy Core',
            'mountain_heart': 'Mountain Heart',
            'earth_titan_shield': 'Earth Titan Shield',
            'crystal_shield': 'Crystal Shield',
            'prismatic_plate': 'Prismatic Plate',
            'ancient_core': 'Ancient Core',
            'war_mechanism': 'War Mechanism',
            'dragon_bulwark': 'Dragon Bulwark',
            'scale_plate': 'Scale Plate',
            'celestial_shield': 'Celestial Shield',
            'heaven_plate': 'Heaven Plate',
            'elder_core': 'Elder Core',
            'ancient_bulwark': 'Ancient Bulwark',
            'primordial_shell': 'Primordial Shell',
            'creation_scale': 'Creation Scale',
            'divine_guard': 'Divine Guard',
            'god_plate': 'God Plate',
            'war_god_shield': 'War God Shield',
            'battle_divinity': 'Battle Divinity',
            'ancient_dragon_shield': 'Ancient Dragon Shield',
            'elder_scale_plate': 'Elder Scale Plate',
            'fortress_titan_core': 'Fortress Titan Core',
            'wall_bulwark': 'Wall Bulwark',
            'celestial_bulwark': 'Celestial Bulwark',
            'divine_titan_plate': 'Divine Titan Plate',
            'primordial_guard': 'Primordial Guard',
            'creation_bulwark': 'Creation Bulwark',
            'elder_war_core': 'Elder War Core',
            'ancient_battle_shield': 'Ancient Battle Shield',
            'divine_scale': 'Divine Scale',
            'god_dragon_shield': 'God Dragon Shield',
            'mountain_divinity': 'Mountain Divinity',
            'earth_god_plate': 'Earth God Plate',
            'ancient_titan_heart': 'Ancient Titan Heart',
            'primordial_bulwark': 'Primordial Bulwark',
            'defense_divinity': 'Defense Divinity',
            'god_fortress': 'God Fortress',
            'eternal_bulwark': 'Eternal Bulwark',
            'immortal_shield': 'Immortal Shield',
            'primordial_scale': 'Primordial Scale',
            'creation_dragon_guard': 'Creation Dragon Guard',
            'war_godhood': 'War Godhood',
            'battle_divine_shield': 'Battle Divine Shield',
            'ancient_fortress_heart': 'Ancient Fortress Heart',
            'elder_wall_shield': 'Elder Wall Shield',
            'celestial_dragon_scale': 'Celestial Dragon Scale',
            'heaven_bulwark': 'Heaven Bulwark',
            'primordial_colossus_core': 'Primordial Colossus Core',
            'creation_titan_shield': 'Creation Titan Shield',
            'elder_guardian_scale': 'Elder Guardian Scale',
            'ancient_dragon_bulwark': 'Ancient Dragon Bulwark',
            'god_titan_heart': 'God Titan Heart',
            'divine_colossus_shield': 'Divine Colossus Shield',
            'ancient_divinity': 'Ancient Divinity',
            'primordial_god_shield': 'Primordial God Shield',
            'fortress_divinity': 'Fortress Divinity',
            'wall_god_bulwark': 'Wall God Bulwark',
            'eternal_titan_core': 'Eternal Titan Core',
            'immortal_colossus_shield': 'Immortal Colossus Shield',
            'primordial_war_divinity': 'Primordial War Divinity',
            'creation_battle_bulwark': 'Creation Battle Bulwark',
            'ancient_dragon_divinity': 'Ancient Dragon Divinity',
            'elder_god_scale_shield': 'Elder God Scale Shield',
            'celestial_fortress_heart': 'Celestial Fortress Heart',
            'heaven_wall_bulwark': 'Heaven Wall Bulwark',
            'creation_divinity': 'Creation Divinity',
            'primordial_guardian_shield': 'Primordial Guardian Shield',
            'elder_god_heart': 'Elder God Heart',
            'ancient_divinity_bulwark': 'Ancient Divinity Bulwark',
            'ragnarok_essence': 'Ragnarok Essence',
            'apocalypse_shield': 'Apocalypse Shield',
            'elemental_god_core': 'Elemental God Core',
            'ultimate_bulwark': 'Ultimate Bulwark'
        };
    }
}

// Export singleton instance
const combatResourcesManager = new CombatResourcesManager();
